"""Adjusted a little

Revision ID: 09d52218c6a0
Revises: 
Create Date: 2024-11-14 17:23:29.711792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d52218c6a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('types_per_dive_site')
    op.drop_table('type')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('common_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('dive_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('region')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('common_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('type_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='type_pkey'),
    sa.UniqueConstraint('type_name', name='type_type_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('types_per_dive_site',
    sa.Column('dive_site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dive_site_id'], ['dive_site.id'], name='types_per_dive_site_dive_site_id_fkey'),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name='types_per_dive_site_type_id_fkey'),
    sa.PrimaryKeyConstraint('dive_site_id', 'type_id', name='types_per_dive_site_pkey')
    )
    # ### end Alembic commands ###
