"""Added UUID to user table

Revision ID: 745ec5f2d2fb
Revises: 09d52218c6a0
Create Date: 2024-12-17 12:18:51.218918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745ec5f2d2fb'
down_revision = '09d52218c6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('animal_rating', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using="user_id::uuid",
               existing_nullable=False)

    with op.batch_alter_table('dive_site', schema=None) as batch_op:
        batch_op.alter_column('max_depth',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('dive_site_category', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('dive_site_rating', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using="user_id::uuid",
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using="user_id::uuid",
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               postgresql_using="user_id::uuid",
               existing_nullable=False,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))

    with op.batch_alter_table('dive_site_rating', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               postgresql_using="user_id::uuid",
               existing_nullable=False)

    with op.batch_alter_table('dive_site_category', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('dive_site', schema=None) as batch_op:
        batch_op.alter_column('max_depth',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('animal_rating', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               postgresql_using="user_id::uuid",
               existing_nullable=False)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
